// <auto-generated />
using DemoProductManagerment.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoProductManagerment.Migrations
{
    [DbContext(typeof(DbProductManagement))]
    [Migration("20210612052321_KhoiTao")]
    partial class KhoiTao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoProductManagerment.Entity.Category", b =>
                {
                    b.Property<int>("cateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("cateId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            cateId = 1,
                            cateName = "Asus"
                        },
                        new
                        {
                            cateId = 2,
                            cateName = "Apple"
                        });
                });

            modelBuilder.Entity("DemoProductManagerment.Entity.Product", b =>
                {
                    b.Property<int>("proId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<int>("cateId")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("proName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("proId");

                    b.HasIndex("cateId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            proId = 1,
                            amount = 100,
                            cateId = 1,
                            price = 10.0,
                            proName = "AsusROG"
                        },
                        new
                        {
                            proId = 2,
                            amount = 100,
                            cateId = 2,
                            price = 10.0,
                            proName = "Macbook"
                        });
                });

            modelBuilder.Entity("DemoProductManagerment.Entity.Product", b =>
                {
                    b.HasOne("DemoProductManagerment.Entity.Category", "category")
                        .WithMany("Products")
                        .HasForeignKey("cateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("DemoProductManagerment.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
